services:

  encoders:
    image: opendigitalradio/encoders
    container_name: odr-encoders
    depends_on:
      - multiplexer
    environment: 
      - TZ=${TZ}
    ports:
      - "8001:8001"
    volumes:
      - "odr:/config"
    command: /config

  multiplexer:
    image: opendigitalradio/dabmux
    container_name: odr-dabmux
    environment: 
      - TZ=${TZ}
    ports:
      - "9001-9016:9001-9016"
      - "9201:9201"
      - "12720-12722:12720-12722"
    volumes:
      - "odr:/config"
    command: /config/odr-dabmux.info

  modulator:
    image: opendigitalradio/dabmod
    container_name: odr-dabmod
    depends_on:
      - multiplexer
    environment: 
      - TZ=${TZ}
    ports:
      - "9400:9400"
    volumes:
      - "odr:/config"
    devices:
      - "${MOD_DEV}"
    command: /config/odr-dabmod.ini

networks:
  odr:
    external: true

volumes:
  odr:
    external: true